apiVersion: v1
kind: PersistentVolume
metadata:
  name: coaster-auth-mysql
spec:
  capacity:
    storage: # To be filled
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: # To be filled
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - # To be filled
---
