apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: coaster-auth
spec:
  volumeName: coaster-auth-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: # To be filled
---
