apiVersion: v1
kind: Service
metadata:
  name: coaster-auth
  namespace: coaster-auth
spec:
  type: LoadBalancer
  selector:
    app: coaster-auth
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
---
